### ISSUE TITLE
Multi-gpu training

### ISSUE THREAD

**Issue by lelelexxx** [visinf/irr#22]
Hi!
     I'm trying to train irr with multi-gpu using the DataParallel provided by pytorch. However, it seems slower than train with single gpu. Ever when I preload all the training data into RAM, the training with multi-gpu is slower than on a single gpu. Where is the bottleneck could be? 
    Thanks!

**Comment by hurjunhwa** [comment]
Hi,

Sorry for the late reply.
I also experienced that it doesn't bring a speed boost when using multiple GPUs. 
I only used the multiple GPU training when the model doesn't fit in one GPU memory.
The bottleneck would be due to some naive implementations of the device assignment such as using cuda() in some places. 
The code was originally developed from Pytorch 0.3, so I didn't use some nice syntax that can be found in the up-to-date version.

Best,
Jun
