### ISSUE TITLE
error while running ./install.sh

### ISSUE THREAD

**Issue by vivasvan1** [visinf/irr#27]
I am trying to run irr on my custom dataset using Google Colab but cannot install the correlation package.

i have successfully installed gcc-4.9

Can you guide me on how can i fix this?

GPU: Telsa T4
Cuda version 10.1

nvidia-smi:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

Error while running install.sh
```
...
...
/usr/local/lib/python3.6/dist-packages/torch/include/c10/core/MemoryFormat.h: In function ‘std::vector<long int> c10::get_channels_last_strides_2d(c10::IntArrayRef)’:
/usr/local/lib/python3.6/dist-packages/torch/include/c10/core/MemoryFormat.h:73:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/usr/local/lib/python3.6/dist-packages/torch/include/c10/core/MemoryFormat.h: In function ‘std::vector<long int> c10::get_channels_last_strides_3d(c10::IntArrayRef)’:
/usr/local/lib/python3.6/dist-packages/torch/include/c10/core/MemoryFormat.h:94:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by hurjunhwa** [comment]
Hi,

Could you may be put these lines in the ``setup.py`` and try again?:
```
'-gencode', 'arch=compute_75,code=sm_75',
'-gencode', 'arch=compute_75,code=compute_75'
```

Best,
Jun

**Comment by coolbeam** [comment]
`
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
`
python=3.6, pytorch=1.5.1

I have the simillar problem in setup correlation layer. 
`
/home/.../anaconda3/envs/k36torch15/lib/python3.6/site-packages/torch/include/c10/util/Optional.h: In instantiation of ‘c10::optional<T>& c10::optional<T>::operator=(c10::optional<T>&&) [with T = bool]’:
/home/.../anaconda3/envs/k36torch15/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/options/upsampling.h:42:3:   required from here
/home/.../anaconda3/envs/k36torch15/lib/python3.6/site-packages/torch/include/c10/util/Optional.h:396:23: error: assignment of read-only location ‘c10::optional<T>::contained_val<bool>()’
       contained_val() = std::move(*rhs);
`

I think this problem is caused by the version of pytorch: pytorch=1.5.1 is not right, maybe a lower version  is better. But, is there a correlation layer that suitable with higher version of pytorch?

**Comment by hurjunhwa** [comment]
Hi, 
Thanks for letting me know.
I haven't tried, but these alternatives can be useful!
https://github.com/ClementPinard/Pytorch-Correlation-extension
https://github.com/princeton-vl/RAFT
