### ISSUE TITLE
undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by RokiaAbdeen** [visinf/irr#31]
I have gotten this error while trying to train the model, what is the problem please?

**Comment by hurjunhwa** [comment]
Could you provide more details on the versions of your pytorch and CUDA? and also which lines of codes cause the error?

**Comment by RokiaAbdeen** [comment]
import correlation_cuda
ImportError: /home/kxd/anaconda3/envs/monodepth2/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

torch version 1.1.0

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

**Comment by hurjunhwa** [comment]
It seems like the issue here:
https://github.com/NVlabs/PWC-Net/issues/11
https://github.com/zllrunning/video-object-removal/issues/21

You can try the different implementation of the correlation layer:
https://github.com/visinf/self-mono-sf/tree/master/models/correlation_package
https://github.com/ClementPinard/Pytorch-Correlation-extension
https://github.com/princeton-vl/RAFT
