### ISSUE TITLE
How can I get the FlyingChairsOcc dataset ?

### ISSUE THREAD

**Issue by RuiFeiHe** [visinf/irr#4]
Hello, I'm very impressed by your amazing work!

The problem is that I cannot find your FlyingChairsOcc dataset or the code that contains how you process data from the original datasets to get your FlyingChairsOcc dataset.

Could you please share your dataset or your processing code?

**Comment by hurjunhwa** [comment]
Hi,

Regarding the dataset, please check our license term first:
https://github.com/visinf/irr/tree/master/flyingchairsocc

And the download link is here (Temporary): (82GB)
https://www.dropbox.com/s/x13u3nd2p5r5rz0/FlyingChairsOcc.tar.gz?dl=0

I am also planning to upload the code that can generate the dataset from a set of raw images.
I will try my best to get it done soon.

**Comment by Blcony** [comment]
> Hi,
> 
> Regarding the dataset, please check our license term first:
> https://github.com/visinf/irr/tree/master/flyingchairsocc
> 
> And the download link is here (Temporary): (82GB)
> https://www.dropbox.com/s/x13u3nd2p5r5rz0/FlyingChairsOcc.tar.gz?dl=0
> 
> I am also planning to upload the code that can generate the dataset from a set of raw images.
> I will try my best to get it done soon.

Hi jun~

I wanted to download your dataset from the link (https://www.dropbox.com/s/x13u3nd2p5r5rz0/FlyingChairsOcc.tar.gz?dl=0), but I failed to download it many times because of the dropbox forbidden error (one of them downloaded 99% and it failed finlly). In fact, I have spent three days downloading the dataset, and I can hardly find other effective methods.

So do you have any other links or methods to download your dataset?

Thank you very much! And I wish to hear from you soon.

Best wishes!

Blcony

**Comment by Blcony** [comment]
> Hello, I'm very impressed by your amazing work!
> 
> The problem is that I cannot find your FlyingChairsOcc dataset or the code that contains how you process data from the original datasets to get your FlyingChairsOcc dataset.
> 
> Could you please share your dataset or your processing code?

Hi RuifeiHe~

Have you downloaded the dataset successfully from the link provided ?

If you have downloaded it successfully, can you share the dataset by something just like BaiduNet?

Thank you very much! I wish to hear from you soon!

Best wishes!

Blcony
