### ISSUE TITLE
Which pytorch version is expected?

### ISSUE THREAD

**Issue by ioky31** [visinf/irr#43]
I tried install pytorch 1.5.0, it is reported a error that "Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method."
I tried install pytorch 0.4.1,but it lacked of some .so file, such as libc10.so and so on.
Please tell me which pytorch version is expected? Or the code needs to be updated.
Could you provide a more detailed Readme?

**Comment by hurjunhwa** [comment]
Hi, 

I checked that it works with pytorch 1.5.0.

Can I ask which model you tried to run? or can you figure out which lines of codes occur the error?

I presume that it can be due to using the previous implementation of the correlation layer.
Using the updated one (https://github.com/visinf/irr/blob/master/models/IRR_PWC.py#L93) may not cause the error.

If not the case, then please let me know again!

**Comment by ioky31** [comment]
Yes, this is the reason. It works correctly now.
Thanks.
